name: agora
description: “Agora”
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  dio: ^4.0.6
  path_provider: ^2.1.2
  path: ^1.8.3
  shimmer: ^3.0.0
  flutter_riverpod:
    path: plugins/flutter_riverpod
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.4
  event_bus: ^2.0.0
  devicelocale: ^0.7.1
  permission_handler: ^11.3.1
  collapsible: ^1.0.0
  flutter_svg: ^2.0.10+1
  shimmer_animation: ^2.2.1
  cached_network_image: ^3.4.0
  flutter_rating_bar: ^4.0.1
  intl_phone_field: ^3.2.0
  scrollable_positioned_list: ^0.3.8

  flutter_gen: any
  photo_view: ^0.15.0
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
