name: agora
description: “Agora”
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  dio: ^4.0.6
  path_provider: ^2.1.2
  path: ^1.8.3
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.4
  event_bus: ^2.0.0
  devicelocale: ^0.7.1
  permission_handler: ^11.3.1
  collapsible: ^1.0.0
  flutter_svg: ^2.0.10+1
  shimmer_animation: ^2.2.1
  cached_network_image: ^3.4.0
  flutter_rating_bar: ^4.0.1
  intl_phone_field: ^3.2.0
  scrollable_positioned_list: ^0.3.5

  flutter_gen: any
  photo_view: ^0.15.0
  video_player: ^2.9.1
  chewie: ^1.8.3
  pinput: ^5.0.0
  timer_count_down: ^2.2.2
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.1
  annotations:
    path: plugins/json_generator/annotations

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: 2.4.11
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  generators:
    path: plugins/json_generator/generators


flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/RobotoCondensed-Thin-w100.ttf
          weight: 100
        - asset: assets/fonts/roboto/RobotoCondensed-ExtraLight-w200.ttf
          weight: 200
        - asset: assets/fonts/roboto/RobotoCondensed-Light-w300.ttf
          weight: 300
        - asset: assets/fonts/roboto/RobotoCondensed-Regular-w400.ttf
          weight: 400
        - asset: assets/fonts/roboto/RobotoCondensed-Medium-w500.ttf
          weight: 500
        - asset: assets/fonts/roboto/RobotoCondensed-SemiBold-w600.ttf
          weight: 600
        - asset: assets/fonts/roboto/RobotoCondensed-Bold-w700.ttf
          weight: 700
        - asset: assets/fonts/roboto/RobotoCondensed-ExtraBold-w800.ttf
          weight: 800
        - asset: assets/fonts/roboto/RobotoCondensed-Black-w900.ttf
          weight: 900

